name: Tests
permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        env:
          VENICE_API_KEY: ${{ secrets.VENICE_API_KEY }}
        run: |
          if [ -f Makefile ]; then make test || true; fi
          if ls tests/*.py 1> /dev/null 2>&1; then pytest -q || true; fi
